dynamo:
  accessKey: *******************
  secretKey: *******************
  signingRegion: us-east-2
  serviceEndpoint: dynamodb.us-east-2.amazonaws.com
server:
  port: 8090
  servlet:
    context-path: /api/v1.0/tweets
